---
- hosts: localhost
  vars_files: vars/vmw_env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks:     
    - name: Deploy the COA cluster on VMware environment
      include: deploy_vmware_cluster_ceph.yml

# - hosts: lab
#   vars_files: vars/vmw_env.yml
#   gather_facts: true
#   become: true
#   serial: 4
#   tasks: 
#     - name: Prepare requirements on all node
#       include: prepare_all_node.yml
