---
service_type: host
addr: 10.1.17.73
hostname: c3-server-c
---
service_type: mon 
placement:
  hosts:
    - c3-server-c
---
service_type: rgw 
service_id: realm.zone
placement:
  hosts:
    - c3-server-c
---
service_type: mgr 
placement:
  hosts:
    - c3-server-c
---
service_type: osd 
service_id: default_drive_group
placement: 
  hosts:
    - c3-server-c
data_devices:
  paths:
    - /dev/sdb
    - /dev/sdc
